language: node_js

node_js:
- 8
- 12
- 14

sudo: false

before_script:
  - npm install

script:
  - npm test

deploy:
  provider: npm
  email: engineering-managers@wikimedia.de
  api_key:
    secure: O0erQiLHaqKq1LQXFytIKskuBNd23Oy4yB/ePOl02sUKBv7O6bmT0bolr101TbttsOg7UXXsJU4XucPSjEAxohbKGC3eLasGyDA4bi5TN1gRPsOpKlfEngk4sCnAHZW7cEPxHWoMG3TceQSxza41Fhuo+dSvXdLeBfnj74CRX5k=
  on:
    tags: true
    branch: master
    condition: "$TRAVIS_NODE_VERSION = 12"

notifications:
  irc:
    channels:
      - "irc.libera.chat#wikidata-feed"
    on_success: never
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} : %{author} %{message} %{build_url}"
