language: node_js

node_js:
- 8
- 12
- node

sudo: false

before_script:
  - npm install

script:
  - npm test

notifications:
  irc:
    channels:
      - "chat.freenode.net#wikidata-feed"
    on_success: never
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} : %{author} %{message} %{build_url}"
