language: php

php:
- 5.3

sudo: false

before_script:
  - nvm install 4

script: npm install && npm test

notifications:
  irc:
    channels:
      - "chat.freenode.net#wikidata-feed"
    on_success: never
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} : %{author} %{message} %{build_url}"

cache:
  directories:
    - $HOME/.composer/cache
