language: node_js

node_js:
- 8
- 12
- 14

sudo: false

before_script:
  - npm install

script:
  - npm test

deploy:
  provider: npm
  email: engineering-managers@wikimedia.de
  api_key:
    secure: JpC5C/PU8CwYpLMYEYqZ/s2dc50KOtm0RR8QC8dFFCxtNl2sfS0r+YNDA5+EvY4rfMJskmlo66J3Zt5sFtIb5LhDKAe6g1jAlGWKAnLhdqgdS2Mx2jz/g2z6swg4+FiLtzqjSSZwjLQz+8wcovEBdx5/Ox6FSJ2k8c6+8JgZZmo=
  on:
    tags: true
    branch: master
    condition: "$TRAVIS_NODE_VERSION = 12"

notifications:
  irc:
    channels:
      - "irc.libera.chat#wikidata-feed"
    on_success: never
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} : %{author} %{message} %{build_url}"
